# Generated by Django 3.1.5 on 2021-01-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_remove_song_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='cnt',
        ),
    ]
