# Generated by Django 3.1.5 on 2021-01-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_remove_keyword_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.URLField(unique=True),
        ),
    ]
