# Generated by Django 3.1.5 on 2021-01-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20210111_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='cnt',
            new_name='play_cnt',
        ),
    ]
