# Generated by Django 3.1.5 on 2021-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_auto_20210111_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
