# Generated by Django 3.1.5 on 2021-01-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
