__all__ = ['DEPARTMENT_CHOICES']

DEVELOPMENT = 'DEV'
CUSTOM_SATISFACTION = 'CS'
MARKETING = 'MK'
PLANNING = 'PL'
BUSINESS_DEVELOPMENT = 'BD'

DEPARTMENT_CHOICES = [
    (DEVELOPMENT, '개발'),
    (CUSTOM_SATISFACTION, 'CS'),
    (MARKETING, '마케팅'),
    (PLANNING, '기획/디자인'),
    (BUSINESS_DEVELOPMENT, '사업개발'),
]