# Generated by Django 3.1.5 on 2021-01-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_answer_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answer_list',
        ),
    ]
